### ISSUE TITLE
I tried the Quest apk. But it doesn't work. I get no response

### ISSUE THREAD

**Issue by Eisenspalter** [teddybear082/godot-gordon-freeman#1]
I tried the Quest apk. But it doesn't work. I get no response

**Comment by teddybear082** [comment]
Thanks, I see you closed this but also wanted to let you know probably this upcoming weekend I'll make a final pcvr and quest release which will probably be my final work on this unless / until someone creates a tighter integration with godot with whisper, GPT4All or a similar locally running AI, and/or local text to speech option, as otherwise I've pushed this general demo as far as I can take it given my knowledge.
